# Generated by Django 5.1.3 on 2024-11-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocker", "0002_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
