# Generated by Django 5.1.3 on 2024-11-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocker", "0003_delete_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Icategory",
            fields=[
                ("icategory_id", models.AutoField(primary_key=True, serialize=False)),
                ("icategory_name", models.CharField(max_length=100, unique=True)),
                ("icategory_des", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "icategory",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Lcategory",
            fields=[
                ("lcategory_id", models.AutoField(primary_key=True, serialize=False)),
                ("lcategory_name", models.CharField(max_length=100, unique=True)),
                ("lcategory_des", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "lcategory",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Notifications",
        ),
    ]
