# Generated by Django 5.1.3 on 2024-11-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocker", "0004_icategory_lcategory_delete_notifications"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Categoryi",
        ),
        migrations.DeleteModel(
            name="Categoryl",
        ),
    ]
