# Generated by Django 5.1.3 on 2024-11-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocker", "0005_delete_categoryi_delete_categoryl"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "notification_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "notification_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "notification_message",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "notification_status",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("notification_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notifications",
                "managed": False,
            },
        ),
    ]
